name: fl_downloader
description: A new flutter plugin project.
version: 0.0.1
#homepage:
environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.10

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.inceptusp.fl_downloader
        pluginClass: FlDownloaderPlugin
      ios:
        pluginClass: FlDownloaderPlugin
